[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd website && npm ci"]

[phases.build]
cmds = ["cd website && npm run build"]

[start]
cmd = "cd website && npx serve dist --listen $PORT"
